### ISSUE TITLE
Chat Tab settings not visible in v11

### ISSUE THREAD

**Issue by KajinStyle** [mclemente/fvtt-chat-tabs#2]
I looked around the Configure Settings and couldn't find this mod. I even made a test world and enabled just this mod and it still wouldn't show up.

I'm not sure how am I suppose to make the custom tabs.

**Comment by Zinxsho** [comment]
same issue, still occurs

**Comment by Akallabeth13666** [comment]
Same

**Comment by Opius134** [comment]
Found the issue. The default module.json file for installing doesn't include the settings code found in the master, Settings.js and TurndownService.js.

go to code>download Zip and pop the 'module' folder into the chat-tabs folder on your foundry instance. Worked for me!
