### ISSUE TITLE
Feat: custom message type

### ISSUE THREAD

**Issue by kai-nashi** [mclemente/fvtt-chat-tabs#3]
it would be good feature to allow defining custom message types to another modules can create non conflicts types. Then by your module separate them to tabs.

Example of module that can require that.
https://foundryvtt.com/packages/change-log

**Comment by kai-nashi** [comment]
Hm... I read foundry API and discover game.messages objects. Unfortunately type is int, my idea is shit. BUT we can define chat sources by Message.speaker. For module above Message.speaker.alias is "Chat Log". I think your chat module has grate potential.

**Comment by Larkinabout** [comment]
Change Log module author here. This would be a great option and save me redoing what already exists with this module.

I'm happy to make changes to the Change Log module to support, such as adding a flag to the chat message. It looks like creating a chat tab with only the Other message type works, but a dedicated message type for when the Change Log module is also installed would be excellent.

If/When there's full support, I'll add this module as a recommended module in the Change Log readme and package page.

**Comment by Nikakto** [comment]
https://github.com/mclemente/fvtt-chat-tabs/pull/5

**Comment by kai-nashi** [comment]
Pull request https://github.com/mclemente/fvtt-chat-tabs/pull/5

**Comment by mclemente** [comment]
I will make some amends to it, like adding its own hook so modules don't need to check if the module is active and using `game.tabbedchat` instead of creating a `window.tabbedchat` just for the call.
