### ISSUE TITLE
Roll is disappearing when no scene is active

### ISSUE THREAD

**Issue by patrickporto** [mclemente/fvtt-chat-tabs#8]
Hello

When the foundry does not have an active scene and the setting "Split In Character and Rolls per Scene" is checked, the roll result disappears after a few minutes or is never shown if you are in another tab.

You may disable any scene through the following macro:

```js
const updates = game.scenes.map(s => ({_id:s.id, active: false}));
Scene.updateDocuments(updates)
```

**Comment by mclemente** [comment]
Just released a fix, check it out and let me know if something is amiss.

**Comment by patrickporto** [comment]
The issue was resolved.
